#!/usr/bin/env python3

import os
import sys
from helpers import get_user_timeline
from nltk import TweetTokenizer
from analyzer import Analyzer
from termcolor import colored


def main():

    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    screen_name = sys.argv[1]


    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    for tweet in get_user_timeline(screen_name):
        # tknzr = TweetTokenizer()
        # final_tweet_chart = tknzr.tokenize(tweet)
        score = Analyzer(positives, negatives)
        score = score.analyze(tweet.lower())
        if score > 0.0:
            print(score, colored(tweet, "green"))
        elif score < 0.0:
            print(score, colored(tweet, "red"))
        else:
            print(score, colored(tweet, "yellow"))




if __name__ == "__main__":
    main()
